<h2>Web Scraping</h2>
<div>Target website: https://football-data.co.uk/data.php </div>

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("https://football-data.co.uk/mmz4281/2526/E0.csv")
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [12]:
# rename col, same names arent common
df.rename(columns={
    "FTHG":'home_goals',
    "FTAG":'away_goals'
},inplace=True)

<p># link structure</p>
"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

In [13]:
root = "https://football-data.co.uk/mmz4281/"

In [14]:
leagues = ["E1","E2","E3","E0"]
frames = []
# appending the dataframe for leagues that got through pattern in frames[]
for category in leagues:
    df = pd.read_csv(root + '2526' + '/' + category + ".csv",encoding_errors='ignore')
    frames.append(df)

In [15]:
# checking how many links
size = len(frames)
# checking first csv
frames[0].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E1,08/08/2025,20:00,Birmingham,Ipswich,1,1,D,0,0,...,1.88,1.98,1.81,2.12,1.88,1.98,1.81,1.94,1.90,2.10
1,E1,09/08/2025,12:30,Charlton,Watford,1,0,H,0,0,...,1.95,1.90,1.95,1.95,1.95,1.90,1.86,1.83,2.03,1.95
2,E1,09/08/2025,12:30,Coventry,Hull,0,0,D,0,0,...,1.88,1.98,1.95,1.95,1.91,1.98,1.87,1.82,1.97,2.01
3,E1,09/08/2025,12:30,Southampton,Wrexham,2,1,H,0,1,...,1.90,1.95,1.75,2.18,1.90,1.95,1.84,1.91,1.92,2.07
4,E1,09/08/2025,15:00,Middlesbrough,Swansea,1,0,H,0,0,...,2.05,1.75,2.00,1.91,2.05,1.82,2.00,1.76,2.16,1.85

<h2>Getting seasons</h2>

In [16]:
leagues = ["E1","E2","E3","E0"]
frames = []
# appending the season dataframe that got through pattern in frames[]
for category in leagues:
    for seasons in range(20,24):
        df = pd.read_csv(root + str(seasons)+str(seasons+1) + '/' + category + ".csv",encoding_errors='ignore')
        # inserting column for identify season
        df.insert(1,'seasons',seasons)
    frames.append(df)

In [17]:
len(frames)
frames[0].head()

,Div,seasons,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,23,04/08/2023,20:00,Sheffield Weds,Southampton,1,2,A,0,...,1.83,0.25,1.91,1.99,1.93,2.00,1.97,2.00,1.88,1.95
1,E1,23,05/08/2023,15:00,Blackburn,West Brom,2,1,H,2,...,1.70,0.00,2.05,1.85,2.07,1.85,2.10,1.88,2.03,1.82
2,E1,23,05/08/2023,15:00,Bristol City,Preston,1,1,D,0,...,1.68,-0.25,1.82,2.08,1.84,2.08,1.88,2.15,1.80,2.04
3,E1,23,05/08/2023,15:00,Middlesbrough,Millwall,0,1,A,0,...,1.77,-0.25,1.80,2.10,1.83,2.10,1.91,2.14,1.85,1.99
4,E1,23,05/08/2023,15:00,Norwich,Hull,2,1,H,1,...,1.92,-0.75,2.06,1.84,2.05,1.86,2.10,1.91,2.01,1.83