In [155]:
import pandas as pd

In [156]:
df = pd.read_csv("StudentsPerformance.csv")

<h1>1. Attributes</h1>

In [157]:
# access data from shape
df.shape

(1000, 8)

In [158]:
# getting access to index attribute
df.index

RangeIndex(start=0, stop=1000, step=1)

In [159]:
# getting access to column attribute
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [160]:
# data types of columns
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

<h1>2. Methods </h1>

In [161]:
# first 5 rows

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [162]:
# Information about dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

In [163]:
# Basic stats
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

<h1>3. Functions </h1>

In [164]:
# obtaining number of rows
len(df)

1000

In [165]:
#columns and count
df.count()

gender                         1000
race/ethnicity                 1000
parental level of education    1000
lunch                          1000
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [166]:
# Highest index / lowest index
max(df.index)
min(df.index)

0

In [167]:
#data type
type(df)

pandas.DataFrame

In [168]:
#round 
round(df,2) 
#No effect as dataset is int

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

<h2>Columns
</h2>

In [169]:
# Selecting one column
df["gender"].head(2)

0    female
1    female
Name: gender, dtype: str

In [170]:
type(df["gender"]) 
# ans series

pandas.Series

In [171]:
#Another way of selecting column 
df.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [172]:
#pitfalls
# "If column with 2 words"
# df.math score -  > Error
# Alternative

In [173]:
df[["gender","math score"]].head(2)

   gender  math score
0  female          72
1  female          69

In [174]:
# adding column
# adding elements different to dataframe
import numpy as np
df.info()
# 1000 elements 
language_score = np.arange(0,1000)
len(language_score)
df["Language Score"] = language_score 
df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4

In [175]:
# random int grades from 0 to 100
# size for 1000 elements
# 0 is inclusive in random, 100 exclusive similar to range
scores =np.random.randint(0,100,size=1000)
len(scores)
df["Language Score"] = scores
df.head()
min(df["Language Score"])

0

In [176]:
# random float number 
scores = np.random.uniform(0,100,size=1000)
df["Language Score"] = scores
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score
0,female,group B,bachelor's degree,standard,none,72,72,74,89.027096
1,female,group C,some college,standard,completed,69,90,88,52.274359
2,female,group B,master's degree,standard,none,90,95,93,58.649628
3,male,group A,associate's degree,free/reduced,none,47,57,44,59.956824
4,male,group C,some college,standard,none,76,78,75,76.229620

In [177]:
# for multiple column using assign
# creating new scores for new columns
score1 = np.random.randint(1,1000,size=1000)
score2 = np.random.randint(1,100,size=1000)
# creating columns - > series are rows
series1 = pd.Series(score1,index=np.arange(0,1000))
series2  = pd.Series(score2,index=np.arange(0,1000))
# Name of column and rows
# df = always to overwrite
df = df.assign(Score1=series1,Score2=series2)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score,Score1,Score2
0,female,group B,bachelor's degree,standard,none,72,72,74,89.027096,681,86
1,female,group C,some college,standard,completed,69,90,88,52.274359,741,22
2,female,group B,master's degree,standard,none,90,95,93,58.649628,198,72
3,male,group A,associate's degree,free/reduced,none,47,57,44,59.956824,473,73
4,male,group C,some college,standard,none,76,78,75,76.229620,682,3

In [178]:
# Using index to add a column at specific location we use insert
# insert(position,name,values)
# no need for df = in insert
df.insert(1,"Test",series1)

In [179]:
df.head(5)

,gender,Test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score,Score1,Score2
0,female,681,group B,bachelor's degree,standard,none,72,72,74,89.027096,681,86
1,female,741,group C,some college,standard,completed,69,90,88,52.274359,741,22
2,female,198,group B,master's degree,standard,none,90,95,93,58.649628,198,72
3,male,473,group A,associate's degree,free/reduced,none,47,57,44,59.956824,473,73
4,male,682,group C,some college,standard,none,76,78,75,76.229620,682,3